version: '3'
services:
  huntress:
    image: darthjee/huntress:latest
    networks:
      - huntress
    ports:
      - 127.0.0.1:3000:80
    volumes:
      - ./huntress/source:/home/app/app

  huntress-debug:
    image: darthjee/huntress:latest
    networks:
      - huntress
    entrypoint: /bin/sh
    volumes:
      - ./huntress/source:/home/app/app


networks:
  huntress:
    name: huntress
