version: '3'
services:
  base: &base
    image: darthjee/huntress:latest
    networks:
      - huntress
    volumes:
      - ./source:/home/app/app
      - ./.node_modules:/home/app/app/node_modules

  huntress:
    <<: *base
    ports:
      - 127.0.0.1:3000:80

  huntress-dev:
    <<: *base
    entrypoint: /bin/sh

networks:
  huntress:
    name: huntress
