services:
  base: &base
    image: darthjee/huntress:latest
    volumes:
      - ./source:/home/app/app
      - ./.node_modules:/home/app/app/node_modules

  huntress:
    <<: *base
    ports:
      - 127.0.0.1:3000:80
    networks:
      - huntress

  huntress-dev:
    <<: *base
    ports:
      - 127.0.0.1:3000:80
    networks:
      - huntress-dev

  huntress-test:
    <<: *base
    entrypoint: /bin/sh
    depends_on: [sample-application]
    networks:
      - huntress-test
  sample-application:
    hostname: sample
    image: darthjee/lemonade
    volumes:
      - ./source/spec/support/sample_config:/home/app/app/config
    networks:
      - huntress-test

networks:
  huntress:
    name: huntress
  huntress-dev:
    name: huntress-dev
  huntress-test:
    name: huntress-test
