version: '3'
services:
  redis:
    image: redis:6.2.4
    networks:
      - huntress-sample-internal

  sample:
    image: huntress_sample
    hostname: sample
    depends_on: [redis]
    networks:
      - huntress-sample-internal
      - huntress

networks:
  huntress-sample-internal:
    name: huntress-sample-internal
  huntress:
    name: huntress
