version: '3'
services:
  base: &base
    image: darthjee/lemonade
    volumes:
      - ./config:/home/app/app/config

  sample:
    <<: *base
    hostname: sample
    networks:
      - huntress

  sample-dev:
    <<: *base
    hostname: sample
    ports:
      - 127.0.0.1:4000:80
    networks:
      - huntress-dev

networks:
  huntress:
    name: huntress
  huntress-dev:
    name: huntress-dev
