version: '3'
services:
  redis:
    image: redis:6.2.4
    networks:
      - huntress-sample-internal

  base: &base
    image: huntress_sample
    depends_on: [redis]
    networks:
      - huntress-sample-internal
      - huntress
    volumes:
      - ./config:/home/app/app/config

  sample:
    <<: *base
    hostname: sample

  sample-dev:
    <<: *base
    ports:
      - 127.0.0.1:3000:80
    volumes:
      - ../../sample/source:/home/app/app
      - ./config:/home/app/app/config

networks:
  huntress-sample-internal:
    name: huntress-sample-internal
  huntress:
    name: huntress
