version: 2
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
jobs:
  test:
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - run:
          name: Set folder
          command: cp source/* ./ -r; rm source -rf
      - run:
          name: NPM install
          command: npm install
      - run:
          name: Jasmine
          command: npx jasmine
