version: 2
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - checks:
          requires: [test]
          filters:
            tags:
              only: /.*/
jobs:
  test:
    docker:
      - image: circleci/node:17
      - image: darthjee/lemonade:latest
        environment:
          LEMONADE_CONFIG={"routes":[{"path":"/","content":"This is the root route"}]}
        name: sample
    steps:
      - checkout
      - run:
          name: Set folder
          command: cp source/* source/.??* ./ -r; rm source -rf
      - run:
          name: NPM install
          command: npm install
      - run:
          name: Jasmine
          command: npm test
  checks:
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - run:
          name: Set folder
          command: cp source/* source/.??* ./ -r; rm source -rf
      - run:
          name: NPM install
          command: npm install
      - run:
          name: Lint
          command: npm run lint
