version: 2
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
jobs:
  test:
    docker:
      - image: circleci/node:17
      - image: darthjee/lemonade:latest
        name: sample
        volumes:
          - ./source/spec/support/sample_config:/home/app/app/config
          - ./source/spec/support/sample_config:/home/app/app
    steps:
      - checkout
      - run:
          name: Set folder
          command: cp source/* ./ -r; rm source -rf
      - run:
          name: NPM install
          command: npm install
      - run:
          name: Jasmine
          command: npx jasmine
